name: Oracle 23c Database

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    container:
      image: swift:5.9-jammy
    services:
      oracle:
        image: gvenzl/oracle-free:23
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: my_user
          APP_USER_PASSWORD: my_password
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set DEBUG specific environment variables
      if: runner.debug == '1'
      run: |
        echo "LOG_LEVEL=trace" >> "$GITHUB_ENV"
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-code-coverage
      env:
        ORA_HOSTNAME: localhost
        ORA_PORT: 1521
        ORA_SERVICE_NAME: FREEPDB1
        ORA_USERNAME: my_user
        ORA_PASSWORD: my_password
    - name: Prepare Code Coverage
      run: llvm-cov export -format="lcov" .build/debug/oracle-nioPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: info.lcov
